### ISSUE TITLE
update downlaod keeps failing

### ISSUE THREAD

**Issue by Blocker64** [simon-wh/PAYDAY-2-BeardLib#675]
For some reason beardlib keeps wanting to update even though its already the latest version after the manual update. i dont know if thats something on my end or not?

**Comment by EdwardHuman** [comment]
I also have similar issues, but it's random mods that are already up to date that needs updated for some reason
![image](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/76008511/e54e19eb-8914-4080-b87d-077e3431b0c9)

**Comment by EdwardHuman** [comment]
Update: It fixed itself after deleting the base mods's folder and reinstalling it with a fresh copy instead of just replacing the files

**Comment by segabl** [comment]
This is due to an API change on MWS, if you use the latest BeardLib version from GitHub, it should be fixed

**Comment by Gamemassa** [comment]
I'm still having the same issue as Edward. All my BeardLib mods keep saying "download has failed".

**Comment by segabl** [comment]
Did you download the latest BeardLib version? make sure you dont have an old version around

**Comment by Gamemassa** [comment]
I went to the code tab of this repository and clicked the stable release link in the Readme section. If there's somewhere else I should be looking, please let me know.

**Comment by segabl** [comment]
that should be fine
